services:
  frontend:
    container_name: plenna-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
