FROM public.ecr.aws/docker/library/node:20-alpine3.19

WORKDIR /app

# Copia apenas os arquivos de dependência primeiro
COPY package*.json ./

RUN npm install

# Copia o restante do código
COPY . .

# Define variáveis para garantir que o React observe mudanças corretamente
ENV CHOKIDAR_USEPOLLING=true
ENV HOST=0.0.0.0

EXPOSE 3000

# Usa o script de desenvolvimento
CMD ["npm", "start"]