export enum Module {
  APPOINTMENTS = 'appointments',
  BANK_ACCOUNTS = 'bankAccounts',
  BILLING = 'billing',
  BILLING_RULES = 'billing-rules',
  CATEGORIES = 'categories',
  CHARGES = 'charges',
  CREDIT_CARDS = 'creditCards',
  CUSTOMERS = 'customers',
  DASHBOARDS = 'dashboards',
  EXPENSES = 'expenses',
  FINANCIAL = 'financial',
  FINANCIAL_SUMMARY = 'financial-summary',
  GATEWAYS = 'gateways',
  GATEWAYS_CONFIG = 'gateways-config',
  INVOICES = 'invoices',
  PAYMENT_METHODS = 'payment-methods',
  REPORTS = 'reports',
  REVENUES = 'revenues',
  SUBCATEGORIES = 'subcategories',
  USERS = 'users',
}
